responses:
  error:
    InvalidYear:
      code: 40001
      message: "Invalid year"
    InvalidLimit:
      code: 40002
      message: "Invalid limit"
    InvalidPage:
      code: 40003
      message: "Invalid page"
    InvalidOrderBy:
      code: 40004
      message: "Invalid orderBy"
    InvalidDirection:
      code: 40005
      message: "Invalid direction"
    MissingTitle:
      code: 40006
      message: "Missing title"
    Unauthorized:
      code: 40101
      message: "Unauthorized request"
    InvalidCredential:
      code: 40102
      message: "Invalid credential"
    FailedAuthorization:
      code: 40103
      message: "Authorization failed"
    NoPermission:
      code: 40301
      message: "No permission to access this endpoint"
    PersonIdNotFound:
      code: 40401
      message: "PersonId not found"
  success:
    MoviesFound:
      code: 20001
      message: "Movie(s) found"
    MoviesNotFound:
      code: 20002
      message: "No movies found with the given search parameters"
    MoviesFoundWithPersonId:
      code: 20003
      message: "Movie(s) found with personId"
    MoviesNotFoundWithPersonId:
      code: 20004
      message: "No movies found with the given personId"


spring:
  jpa:
    hibernate:
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


