spring:
  jpa:
    hibernate:
      # The following strategy tells Hibernate not to apply any naming conversion between camelCase and snake_case.
      # Instead, it will use the exact names you define in your Java code.
      #
      # Background:
      # Spring Boot, by default, uses SpringPhysicalNamingStrategy, which converts camelCase to snake_case. For example:
      #   - Entity Field Name (camelCase): firstName
      #   - Database Column Name (snake_case): first_name
      #
      # This means if you have an entity class with a field named firstName, by default, Spring Boot will map it to a column named first_name in the database.
      # With the following strategy, if your entity class has a field named firstName, Hibernate will map it to a column named firstName in the database, without converting it to snake_case.
      # If we don't use this strategy, when we use hibernate to interact with the database, we name our column firstName, but hibernate will look for column named first_name, which can't find in the database, and then cause error.
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl