package com.example.movie_service.integration;


import com.example.movie_service.dto.MovieSearchResultDTO;
import com.example.movie_service.response.CustomResponse;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.web.client.TestRestTemplate;
import org.springframework.boot.test.web.server.LocalServerPort;
import org.springframework.boot.testcontainers.service.connection.ServiceConnection;
import org.springframework.core.ParameterizedTypeReference;
import org.springframework.http.HttpMethod;
import org.springframework.http.ResponseEntity;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.DynamicPropertyRegistry;
import org.springframework.test.context.DynamicPropertySource;
import org.springframework.web.util.UriComponentsBuilder;
import org.testcontainers.containers.MySQLContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;

import javax.sql.DataSource;
import java.net.URI;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;
import static org.junit.jupiter.api.Assertions.*;

@ActiveProfiles("test")
@Testcontainers
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
public class ControllerIT {


    private static final String SQL_VERSION = "mysql:8.0.39";

    @SuppressWarnings({"resource"})
    // "resource":
    // Since I use @Container here, JUnit will manage the lifecycle of the test
    // container, it also closes the container at the appropriate time, so we don't need to manually handle closing,
    // so we can ignore the warning from the 'MySQLContainer<SELF>' used without 'try'-with-resources statement
    // The try-with-resources  automatically close resources when they are no longer needed. JUnit here does the job
    // for us, so we don't need to use try-with-resources
    // "unused":
    // The mysqlContainer is used because in the setUp(), the database url has the mysqlContainer database name,
    // so the mysqlContainer is actually used.
    @Container
    public static MySQLContainer<?> mysqlContainer = new MySQLContainer<>(SQL_VERSION)
            .withDatabaseName("testDB")
            .withUsername("testUser")
            .withPassword("testPassword")
            .withReuse(true);

    @DynamicPropertySource
    static void setUpProperties(DynamicPropertyRegistry registry) {
        registry.add("spring.datasource.url", mysqlContainer::getJdbcUrl);
        registry.add("spring.datasource.username", mysqlContainer::getUsername);
        registry.add("spring.datasource.password", mysqlContainer::getPassword);
        registry.add("spring.datasource.driver-class-name", mysqlContainer::getDriverClassName);
    }


    @Autowired
    private TestRestTemplate restTemplate;

    @Autowired
    private DataSource dataSource;

    @Autowired
    private DataInitializerService dataInitializerService;

    // Get the random port generated by @SpringBootTest
    @LocalServerPort
    private int port;

    private static final String protocolAndHost = "http://localhost:";
    private String searchMoviePath;

    @BeforeEach
    public void setUp(){
        String baseUrl = protocolAndHost + port + "/v1/api";
        searchMoviePath = baseUrl + "/movies";

        dataInitializerService.checkDatabaseEmpty();
        dataInitializerService.initializeData();
    }

    @AfterEach
    public void afterEach() {
        // Clean the database
        dataInitializerService.clearDatabase();
    }

    @Test
    public void testDatabaseConnection() throws SQLException {
        // Log the JDBC URL to ensure it's pointing to the Testcontainers instance
        try (Connection connection = dataSource.getConnection()) {
            System.out.println("Connected to database: " + connection.getMetaData().getURL());
        }
    }


    @Test
    void testSearchMoviesMovieFound() {
        // Define URI with query param
        URI uri = UriComponentsBuilder.fromHttpUrl(searchMoviePath)
                .queryParam("title", "Knight")
                .build().toUri();

        // Define the response type using ParameterizedTypeReference
        ParameterizedTypeReference<CustomResponse<List<MovieSearchResultDTO>>> responseType =
                new ParameterizedTypeReference<CustomResponse<List<MovieSearchResultDTO>>>() {};


        // Perform a GET request to the controller
        ResponseEntity<CustomResponse<List<MovieSearchResultDTO>>> results = restTemplate.exchange
                (uri, HttpMethod.GET, null, responseType);

        System.out.println(results.getStatusCode());
        // Assert
        assertTrue(results.getStatusCode().is2xxSuccessful());
        CustomResponse<List<MovieSearchResultDTO>> customResponse = results.getBody();
        assertNotNull(customResponse);
        // Assert that the return code is 20001, representing movies found
        assertEquals(customResponse.getCode(), 20001);
        List<MovieSearchResultDTO> movieList = customResponse.getData();
        // Assert there are 3 movies
        assertEquals(movieList.size(), 3);
        // Assert 1st movie is The Dark Knight
        assertEquals(movieList.get(0).getTitle(), "The Dark Knight");
        assertEquals(movieList.get(1).getTitle(), "The Dark Knight Rises");
        assertEquals(movieList.get(2).getTitle(), "The Dark Knight Rises Again");
    }

    @Test
    void testSearchMoviesNotFound() {
        URI uri = UriComponentsBuilder.fromHttpUrl(searchMoviePath)
                .queryParam("title", "Miss Jerry")
                .build().toUri();
    }
}
